name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-latest, unbuntu-latest]
        include:
        - os: macos-latest
          GOOS: darwin
          GOARCH: amd64
          CGO_ENABLED: 1
        - os: macos-latest
          GOOS: darwin
          GOARCH: arm
          CGO_ENABLED: 1
        - os: ubuntu-latest
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 1
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: GOOS=${{matrix.GOOS}} GOARCH=${{matrix.GOARCH}} CGO_ENABLED=${{matrix.CGO_ENABLED}} go build main.go

