name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [amd64]
        cgo: [1]
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
        - os: macos-latest
          GOOS: darwin
        - os: macos-latest
          GOOS: darwin
          arch: arm64
        - os: ubuntu-latest
          GOOS: linux
        - os: windows-latest
          GOOS: windows
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: GOOS=${{matrix.GOOS}} GOARCH=${{matrix.arch}} CGO_ENABLED=${{matrix.cgo}} go build main.go

